USE quicktour;

INSERT INTO excursions VALUES (0, 1, 'Excursion on old town', false, 50);
INSERT INTO excursions VALUES (0, 1, 'Excursion on theatres', true, 20);
INSERT INTO excursions VALUES (0, 1, 'Excursion3', false, 60);
INSERT INTO excursions VALUES (0, 2, 'Excursion1', true, 30);
INSERT INTO excursions VALUES (0, 2, 'Excursion2', false, 50);
INSERT INTO excursions VALUES (0, 3, 'Excursion1', false, 50);
INSERT INTO excursions VALUES (0, 3, 'Excursion2', false, 50);
INSERT INTO excursions VALUES (0, 3, 'Excursion3', true, 150);
INSERT INTO excursions VALUES (0, 4, 'Excursion1', false, 50);
INSERT INTO excursions VALUES (0, 4, 'Excursion2', true, 50);
INSERT INTO excursions VALUES (0, 5, 'Excursion1', false, 50);
INSERT INTO excursions VALUES (0, 5, 'Excursion2', true, 50);
INSERT INTO excursions VALUES (0, 5, 'Excursion3', true, 50);
INSERT INTO excursions VALUES (0, 6, 'Excursion1', false, 50);
INSERT INTO excursions VALUES (0, 6, 'Excursion2', true, 50);
INSERT INTO excursions VALUES (0, 6, 'Excursion3', true, 50);
INSERT INTO excursions VALUES (0, 6, 'Excursion4', false, 50);
INSERT INTO excursions VALUES (0, 7, 'Excursion1', false, 50);
