insert into comments(user_id, tour_id, comment) values(
2,1, 'Nullam consectetur varius consectetur. Suspendisse ut tortor fringilla, ornare lacus tempor, venenatis est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus ante, dictum nec eros et, volutpat consequat ante. Sed vulputate sapien ut aliquet consectetur. Quisque convallis gravida massa, sed hendrerit arcu laoreet at. Fusce quis iaculis quam, eget rhoncus turpis. Nullam iaculis eget arcu nec malesuada. Curabitur augue magna, suscipit eu magna in, condimentum tristique augue. Etiam eu interdum purus, eget egestas nisl. Sed vestibulum tortor in elit volutpat euismod. Fusce a felis volutpat, volutpat lorem a, consequat orci. Etiam nec nisl ac mi lobortis varius.'
 ),(
3,1, 'Sed pretium, nibh vel dictum rutrum, lectus lorem porttitor lectus, et porttitor dui nunc sed ipsum. Nam a dolor in dui gravida ornare et nec sem. Vivamus eget enim ornare, pharetra magna ac, cursus metus. In quis commodo libero, sit amet accumsan risus. Etiam laoreet felis eu mi malesuada auctor. Donec et ultricies elit. Mauris et tortor vitae urna ornare pharetra vitae vel sem. Maecenas tristique quam sed tempor ultrices. Donec ut leo odio. Integer venenatis venenatis odio, eu pharetra orci consequat pretium. Sed lacinia rutrum arcu, non condimentum neque condimentum et.'
  ),(
4,2, 'In hac habitasse platea dictumst. Curabitur rutrum justo eget mauris iaculis, at adipiscing massa feugiat. Sed rhoncus lacinia nisi. In at lobortis purus. Maecenas metus dui, aliquet eget semper ac, sagittis tincidunt elit. Fusce ante nibh, ultricies dignissim pellentesque eu, tincidunt consequat erat. Ut varius diam in erat consectetur ultricies. Curabitur vel nunc non lectus posuere aliquam et et quam. Nam tincidunt interdum tellus sit amet convallis. Sed velit ipsum, pulvinar a viverra vel, vestibulum at nisl. Nunc elementum tempor euismod. Phasellus porttitor nisl ut enim malesuada, consequat sodales erat faucibus. Vivamus dignissim pellentesque tincidunt. Morbi dapibus velit sit amet vulputate consequat. Etiam pharetra euismod eros, et sagittis turpis sagittis id.'
),(
3,2, 'In hac habitasse platea dictumst. Curabitur rutrum justo eget mauris iaculis, at adipiscing massa feugiat. Sed rhoncus lacinia nisi. In at lobortis purus. Maecenas metus dui, aliquet eget semper ac, sagittis tincidunt elit. Fusce ante nibh, ultricies dignissim pellentesque eu, tincidunt consequat erat. Ut varius diam in erat consectetur ultricies. Curabitur vel nunc non lectus posuere aliquam et et quam. Nam tincidunt interdum tellus sit amet convallis. Sed velit ipsum, pulvinar a viverra vel, vestibulum at nisl. Nunc elementum tempor euismod. Phasellus porttitor nisl ut enim malesuada, consequat sodales erat faucibus. Vivamus dignissim pellentesque tincidunt. Morbi dapibus velit sit amet vulputate consequat. Etiam pharetra euismod eros, et sagittis turpis sagittis id.'
)
;